---
keyboards:
  en_mac_ie:
    name: English Mac (IE)
    icon: ie.png
    variant: mac
    model: pc105
    layout: gb
  en_us:
    name: English (US)
    icon: us.png
    model: pc105
    layout: us

selected: en_mac_ie
